language: python
sudo: false
env:
  global:
    - INSTALL_STRING=".[event-file-poller]" TEST_TYPE=prcheck HYPOTHESIS_PROFILE=ci
matrix:
  include:
  - python: "3.8"
    dist: xenial
    sudo: true
    env: INSTALL_STRING="."
    arch:
      - arm64
  - python: "3.8"
    dist: xenial
    sudo: true
    arch:
      - arm64
  - python: "3.7"
    dist: xenial
    sudo: true
    arch:
      - arm64
  - python: "3.6"
    arch:
      - arm64
  - python: "2.7"
    env: TEST_TYPE=prcheck-py2
    arch:
      - arm64
install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels;
    fi
  - pip install -r requirements-dev.txt -r requirements-docs.txt
  - pip install -e "$INSTALL_STRING"
script:
  - env
  - make $TEST_TYPE
after_success:
  - if [[ $TEST_TYPE == 'prcheck-py2' ]]; then pip install codecov==2.0.5 && codecov; fi
